Modulo 2/django/mbproject/loanapp/urls.py
from django.urls import path
from loanapp.views import *

urlpatterns  = [
    path('libro/agregar/', agregar_libro, name='agregar_libro'),
    path('libro/editar/<int:id>', editar_libro, name='editar_libro'),
    path('libro/eliminar/<int:id>', eliminar_libro, name='eliminar_libro'),     
]

Modulo 2/django/mbproject/mbproject/urls.py
from django.contrib import admin
from django.urls import path, include
from loanapp.views import *

urlpatterns = [
    path('admin/', admin.site.urls),    
    path('', home, name='inicio'),
    path('loanapp/', include('loanapp.urls')),
    path('usuario/registrar/', registrar_usuario, name='registrar_usuario'),
    path('usuario/login/', login_, name='login_user'),
    path('usuario/logout/', logout_, name='logout_user')          
]

Modulo 2/django/mbproject/loanapp/models.py
from django.db import models
from django.contrib.auth.models import User


opciones_prestamo = [
    ('P', 'Prestado'),
    ('E', 'Entregado'),
    ('Pe', 'Perdido')
] 

opcion = [
    ('F', 'Femenino'),
    ('M', 'Masculino')
]

class Libro(models.Model):
    serial = models.CharField(max_length=10, default="N/A")
    titulo = models.CharField(max_length=80)
    autor = models.CharField(max_length=50)
    genero = models.CharField(max_length=40)
    editorial = models.CharField(max_length=60, default="N/A")
    pag = models.PositiveIntegerField()
    precio = models.FloatField()    
    notas = models.TextField(max_length=500, default='N/A', blank=True)


class Persona(models.Model):
    usuario = models.OneToOneField(User, on_delete=models.CASCADE)             
    nombre = models.CharField(max_length=80)    
    apellido = models.CharField(max_length=100)
    direccion = models.CharField(max_length=150)
    telefono = models.CharField(max_length=12)
    correo = models.EmailField(max_length=25)
    sexo = models.CharField(max_length=2, choices=opcion, default='M')

class Prestamo(models.Model):
    persona = models.ForeignKey(Persona, on_delete=models.CASCADE)
    libro = models.ForeignKey(Libro, on_delete=models.CASCADE)
    fprestamo = models.DateTimeField()
    fentrega = models.DateTimeField(null=True)
    estado = models.CharField(max_length=2, choices=opciones_prestamo)












Modulo 2/django/mbproject/loanapp/forms.py
from django.forms import ModelForm
from django import forms

from loanapp.models import *

class UsuarioForm(forms.Form):
    usuario = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    correo = forms.EmailField(max_length=50, widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'placeholder': 'nombre@correo'
    }))
    password = forms.CharField(max_length=12, widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    password_verificar = forms.CharField(max_length=12, widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

class LoginForm(forms.Form):
    usuario = forms.CharField(max_length=20, widget=forms.TextInput(attrs={
        'class': 'form-control'
    }))
    password = forms.CharField(max_length=12, widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))








Modulo 2/django/mbproject/loanapp/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse, response
from django.urls import reverse
from loanapp.models import *
from loanapp.forms import *
from django.contrib.auth.models import User
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required


def home(request):
    contexto = dict()
    libros = Libro.objects.all()
    for libro in libros:
        libro.precio = round(libro.precio)
    contexto['libros'] = libros      
    return render(request, 'index.html', contexto)

@login_required(login_url='/usuario/login/')
def agregar_libro(request):
    if request.method == 'POST':
        serial = request.POST['serial']
        titulo = request.POST['titulo']
        autor = request.POST['autor']
        genero = request.POST['genero']
        editorial = request.POST['editorial']
        pag = request.POST['pag']
        precio = request.POST['precio']
        notas = request.POST['notas']
        try:
            libro = Libro.objects.create(serial=serial, titulo=titulo, autor=autor, genero=genero, editorial=editorial, pag=pag, precio=precio, notas=notas)
            estado = True
            contexto = {
                'estado': estado,
                'libro': libro
                }
        except ValueError as e:
            estado = False
            contexto = {
                'estado': estado,
                'titulo': titulo,
                'error': e
                }
        return render(request, 'respuesta.html', contexto)        
    else:    
        return render(request, 'agregar_libro.html')

@login_required(login_url='/usuario/login/')
def editar_libro(request, id):
    libro = Libro.objects.get(id=id)
    if request.method == 'POST':
        serial = request.POST['serial']
        titulo = request.POST['titulo']
        autor = request.POST['autor']
        genero = request.POST['genero']
        editorial = request.POST['editorial']
        pag = request.POST['pag']
        precio = request.POST['precio']
        notas = request.POST['notas']
        libro.serial = serial
        libro.titulo = titulo
        libro.autor = autor
        libro.genero = genero
        libro.editorial = editorial
        libro.pag = pag
        libro.precio = precio
        libro.notas = notas
        try:
            libro.save()
            estado = True
            contexto = {
                'estado': estado,
                'libro': libro
                }
        except:
            estado = False
            contexto = {
                'estado': estado,
                'titulo': titulo
                }
        return render(request, 'respuesta.html', contexto) 
    else:                        
        return render(request, 'editar_libro.html', {'libro': libro})

@login_required(login_url='/usuario/login/')
def eliminar_libro(request, id):
    libro = Libro.objects.get(id=id)
    libro.delete()
    return redirect(reverse('inicio'))

def registrar_usuario(request):
    if request.method == 'POST':
        form = UsuarioForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data['usuario']
            correo = form.cleaned_data['correo']
            password = form.cleaned_data['password']
            password_verificar = form.cleaned_data['password_verificar']
            if password == password_verificar:
                User.objects.create_user(usuario, correo, password)
                messages.success(request, 'Usuario creado correctamente.')
                return redirect(reverse('registrar_usuario'))
            else:
                messages.warning(request, 'Contraseña no coincide')
                return redirect(reverse('registrar_usuario'))            
        else:
            messages.warning(request, 'Datos no validos')
            return redirect(reverse('registrar_usuario')) 
    else:      
        contexto = dict()
        contexto['UsuarioForm'] = UsuarioForm()
        return render(request, 'registrar_usuario.html', contexto)

def login_(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            usuario = form.cleaned_data['usuario']
            password = form.cleaned_data['password']
            user = authenticate(username=usuario, password=password)
            if user is not None:
                login(request, user)
                return redirect(reverse('inicio'))
            else:
                messages.warning(request, 'El usuario y/o contraseña es incorrecto')
                return redirect(reverse('login_user'))
        else:
            messages.warning(request, 'Error al leer los datos enviados')
            return redirect(reverse('login_user'))            
    else:
        contexto = dict()
        contexto['formLogin'] = LoginForm()
        return render(request, 'login_usuario.html', contexto)
        
@login_required(login_url='/usuario/login/')
def logout_(request):
    logout(request)
    return redirect(reverse('inicio'))




Modulo 2/django/mbproject/loanapp/templates/agregar_libro.html
{% extends 'base.html' %}

{% block titulo %} Libros{% endblock titulo %}

{% block tema %}
    Agregar Libro                           
{% endblock tema %}

{% block contenido %}
    <form action="{% url 'agregar_libro' %}" method="post">
        {% csrf_token %}
        {% include 'formulario.html' %}
    </form>           
{% endblock contenido %}

Modulo 2/django/mbproject/loanapp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es-CO">
    <head>
        <meta charset="UTF-8">
        <meta name="keywords" content="Book, libro, biblioteca, library">
        <meta name="description" content="Sistema de gestion de recursos bibliograficos"> 
        <meta name="author" content="G165 - Misiontic 2022 Ruta 1"> 
        <!-- Etiquetas opcionales -->        
        <meta name="viewport" content="width=device-width, initial-scale=1.0">      
        <link rel="icon" href="favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous">        
        <title>Biblioteca | {% block titulo %}{% endblock titulo %}</title>                         
    </head>
    <body>        
        <header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
            <a class="navbar-brand col-md-3 col-lg-2 me-0 px-3" href="#">
                <i class="fas fa-book-reader me-2"></i>
                Biblioteca Personal
            </a>
            <div class="nav nav-pills" >
               
               {% if user.is_authenticated %}
                  <li class="nav-item">
                    <a href="" class="nav-link text-white">{{user.username}}</a>
                  </li>
                  <li class="nav-item">
                    <a href="{% url 'logout_user' %}" class="nav-link text-white">Salir</a>
                  </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'login_user' %}">Ingresar</a>
                 </li>
                 <li class="nav-item">
                     <a class="nav-link text-white" href="{% url 'registrar_usuario' %}">Registrar</a>
                 </li>
               {% endif %}                    
            </div>            
        </header>
        <div class="container-fluid">
            <div class="row">
                <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                    <div class="position-sticky pt-3">
                        <ul class="nav flex-column">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'inicio' %}">                                    
                                    Home
                                </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'agregar_libro' %}">                                    
                                    Agregar
                                </a>
                            </li>                                                   
                        </ul>
                    </div>    
                </nav>
                <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
                    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                        <h1 class="h2">
                            {% block tema %}
                            
                            {% endblock tema %}
                        </h1>
                    </div>
                        
                        {% block contenido %}
                            
                        {% endblock contenido %}
                            
                    
                </main>
            </div>
        </div>    
               
        
        <footer class="text-muted py-5">
          <div class="container">
            <p class="float-end mb-1">
              <a href="#">Back to top</a>
            </p>
            <p class="mb-1">Copyright &copy; 2021 Misiontic Ruta 1 - Grupos 96, 165 y 185</p>
            <p class="mb-0">Curso completo <a href="https://github.com/jguerrero10/misiontic2020R1">Link Github</a></p>
          </div>
        </footer>
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"></script>
    </body>
</html>


Modulo 2/django/mbproject/loanapp/templates/correcto.html
<h4>El datos se almacenó correctamente</h4>

<p>   
    
    <p><strong>Serial</strong>: {{libro.serial}}</p>
    <p><strong>Titulo</strong>: {{libro.titulo}}</p>
    <p><strong>Autor</strong>: {{libro.autor}}</p>     
   
        
</p>

Modulo 2/django/mbproject/loanapp/templates/editar_libro.html
{% extends 'base.html' %}

{% block titulo %}
    Libros
{% endblock titulo %}

{% block tema %}
    Editar Libro                            
{% endblock tema %}

{% block contenido %}
<form action="{% url 'editar_libro' libro.id %}" method="post">
    {% csrf_token %}
    {% include 'formulario.html' %}
</form>                     
{% endblock contenido %}

Modulo 2/django/mbproject/loanapp/templates/fallo.html
<h4>Problema al guardar los datos</h4>

<p> 
    No fue posible guardar el libro siguiente: 
          
    <p><strong>Titulo</strong>: {{titulo}}</p> 
    <p>Error: {{error}}</p>             
</p>

Modulo 2/django/mbproject/loanapp/templates/formulario.html
<div class="row g-3 align-items-center">
    <div class="col-1">
        <label class="col-form-label" for="serial">Serial</label>
    </div>
    <div class="col-11">
         <input id="serial" value="{{libro.serial}}"  name="serial" class="form-control" type="text">
    </div> 
    <div class="col-1">
     <label class="col-form-label" for="titulo">titulo</label>
 </div>
 <div class="col-11">
      <input id="titulo" name="titulo" value="{{libro.titulo}}" class="form-control" type="text">
 </div>
 <div class="col-1">
     <label class="col-form-label" for="autor">Autor</label>
 </div>
 <div class="col-11">
      <input id="autor" name="autor" value="{{libro.autor}}" class="form-control" type="text">
 </div>
 <div class="col-1">
     <label class="col-form-label" for="genero">Género</label>
 </div>
 <div class="col-11">
      <input id="genero" name="genero" value="{{libro.genero}}" class="form-control" type="text">
 </div>
 <div class="col-1">
     <label class="col-form-label" for="editorial">Editorial</label>
 </div>
 <div class="col-11">      
      <input id="editorial" value="{{libro.editorial}}" name="editorial" class="form-control" type="text">
 </div>
 <div class="col-1">
     <label class="col-form-label" for="pag">Página</label>
 </div>
 <div class="col-11">
      <input id="pag" name="pag" value="{{libro.pag}}" class="form-control" type="number" min="0">
 </div>
 <div class="col-1">
     <label class="col-form-label" for="precio">Precio</label>
 </div>
 <div class="col-11">
      <input id="precio" value="{{libro.precio}}" name="precio" class="form-control" type="number" min="0">
 </div>
 <div class="col-1">
     <label class="col-form-label" for="notas">Notas</label>
 </div>
 <div class="col-11">
     <textarea class="form-control" name="notas" id="notas" cols="30" rows="10">
        {{libro.notas}}
     </textarea>
 </div>
 <div class="col-4">
     <button type="submit" class="btn-primary">Enviar Info</button>
     <button type="reset" class="btn-danger">Restablecer</button>
 </div>
 </div>  

Modulo 2/django/mbproject/loanapp/templates/index.html
{% extends 'base.html' %}

{% block titulo %}Inicio{% endblock titulo %}
{% block tema %}
    Listado de Libros                            
{% endblock tema %}

{% block contenido %}
<div class="table-responsive">
<table class="table table-striped table-sm">
    <tr>
        <th>id</th>
        <th>Nombre</th>
        <th>Editorial</th>
        <th>Autor</th>
        <th>Género</th>
        <th>Páginas</th>
        <th>Precio</th>
        <th>Acción</th>
    </tr>
   
   {% for libro in libros  %}
       <tr>
           <td>{{libro.id}}</td>
           <td>{{libro.titulo}}</td>
           <td>{{libro.editorial}}</td>
           <td>{{libro.autor}}</td>
           <td>{{libro.genero}}</td>
           <td>{{libro.pag}}</td>
           <td>${{libro.precio}}</td>
           <td>
               <a href="{% url 'editar_libro' libro.id %}" class="btn btn-warning">Editar</a>
                <a href="{% url 'eliminar_libro' libro.id %}" class="btn btn-danger">Eliminar</a>   
        </td>
       </tr>
   {% endfor %}
       
</table> 
</div>                           
{% endblock contenido %}

Modulo 2/django/mbproject/loanapp/templates/login_usuario.html
{% extends 'base.html' %}

{% block titulo %}
    Login
{% endblock titulo %}

{% block tema %}
    Acceso                           
{% endblock tema %}

{% block contenido %}
    <div class="row">
        <div class="col-6">
            <div class="card">
                <div class="card-header">
                    <h6>Acceder al Sitio | Login</h6>
                </div>
                <div class="card-body">
                    {% if messages %}
                    {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                        {{ message }}
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                    </div>
                    {% endfor %}
                    
                {% endif %}
                    <form action="{% url 'login_user' %}" method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                          <label for="id_usuario" class="form-label">{{formLogin.usuario.label}}</label>
                          {{formLogin.usuario}}                         
                        </div>
                        <div class="mb-3">
                          <label for="id_password" class="form-label">{{formLogin.password.label}}</label>
                          {{formLogin.password}}
                        </div>                        
                        <button type="submit" class="btn btn-primary">Ingresar</button>
                      </form>
                </div>
            </div>
        </div>
    </div>
                     
{% endblock contenido %}

Modulo 2/django/mbproject/loanapp/templates/registrar_usuario.html
{% extends 'base.html' %}

{% block titulo %}
    Usuarios
{% endblock titulo %}

{% block tema %}
    Agregar Usuario                            
{% endblock tema %}

{% block contenido %}
<div class="row">
    <div class="col-6">
        <form action="{% url 'registrar_usuario' %}" method="post"> 
            {% if messages %}
                {% for message in messages %}
                <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                    {{ message }}
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
                {% endfor %}
                
            {% endif %}          
            {% csrf_token %}            
            <div class="row mb-3">
                {{UsuarioForm.usuario.label}}
                {{UsuarioForm.usuario}}
            </div>
            <div class="row mb-3">
                {{UsuarioForm.correo.label}}
                {{UsuarioForm.correo}}
            </div>
            <div class="row mb-3">
                {{UsuarioForm.password.label}}
                {{UsuarioForm.password}}
            </div>
            <div class="row mb-3">
                {{UsuarioForm.password_verificar.label}}
                {{UsuarioForm.password_verificar}}
            </div> 
            <div class="row m-1">
                <div class="col-2">
                    <button type="submit" class="btn btn-primary">Registrar</button>                    
                </div>
                <div class="col-2">
                    <button type="reset" class="btn btn-secondary">Resetear</button>
                </div>                
            </div>        
        </form>        
    </div>
</div>
                     
{% endblock contenido %}

Modulo 2/django/mbproject/loanapp/templates/respuesta.html
{% extends 'base.html' %}

{% block titulo %}
    Libros
{% endblock titulo %}

{% block tema %}
    Guardar - Libros                           
{% endblock tema %}

{% block contenido %}
<h4>Libro - Guardar</h4>  


{% if estado == True %}
    {% include 'correcto.html' %}
{% else %}
    {% include 'fallo.html' %}
{% endif %}
    
{% endblock contenido %}